# ==========================================
# QUESTION 1
# SCHOOL CAFETERIA MEAL PLANNING SYSTEM
# ==========================================
#
# Data structures used:
#   - list of tuples: raw meal_data records (student_name, meal_type, daily_price)
#   - dictionary: used repeatedly to group/aggregate data by student or by meal
#
# Assumptions:
#   - "daily_price" is what a student spends on that meal PER DAY.
#   - A school week = 5 days, so weekly spend = daily_price * DAYS_PER_WEEK.
#   - Each tuple in meal_data represents one student's fixed meal choice for the week.

# ---- Constants (avoid hard-coding rules/thresholds) ----
DAYS_PER_WEEK = 5
HIGH_SPENDER_THRESHOLD = 15000  # UGX per week


def group_by_meal(meal_data):
    """Group students by the meal they prefer.
    Returns: dict {meal_type: [student_name, student_name, ...]}
    """
    meal_groups = {}
    for name, meal, price in meal_data:          # loop through every record
        if meal not in meal_groups:               # conditional: new meal seen?
            meal_groups[meal] = []
        meal_groups[meal].append(name)
    return meal_groups


def calculate_weekly_spending(meal_data):
    """Calculate each student's weekly spending.
    Returns: dict {student_name: weekly_amount}
    """
    weekly_spending = {}
    for name, meal, price in meal_data:
        weekly_amount = price * DAYS_PER_WEEK
        # a student could theoretically appear more than once; add up if so
        weekly_spending[name] = weekly_spending.get(name, 0) + weekly_amount
    return weekly_spending


def find_high_spenders(weekly_spending):
    """Return list of (student, amount) spending above the threshold."""
    high_spenders = []
    for name, amount in weekly_spending.items():
        if amount > HIGH_SPENDER_THRESHOLD:        # conditional check
            high_spenders.append((name, amount))
    return high_spenders


def calculate_meal_revenue(meal_data):
    """Calculate total weekly revenue generated by each meal type.
    Returns: dict {meal_type: total_weekly_revenue}
    """
    meal_revenue = {}
    for name, meal, price in meal_data:
        weekly_amount = price * DAYS_PER_WEEK
        meal_revenue[meal] = meal_revenue.get(meal, 0) + weekly_amount
    return meal_revenue


def find_most_popular_meal(meal_groups):
    """Most popular meal = meal chosen by the most students."""
    most_popular = None
    highest_count = 0
    for meal, students in meal_groups.items():
        if len(students) > highest_count:
            highest_count = len(students)
            most_popular = meal
    return most_popular, highest_count


def generate_report(meal_data):
    """Build and print the full cafeteria report."""
    meal_groups = group_by_meal(meal_data)
    weekly_spending = calculate_weekly_spending(meal_data)
    high_spenders = find_high_spenders(weekly_spending)
    meal_revenue = calculate_meal_revenue(meal_data)
    popular_meal, popular_count = find_most_popular_meal(meal_groups)

    print("=" * 50)
    print("CAFETERIA WEEKLY REPORT")
    print("=" * 50)

    print("\n--- Students Grouped by Meal Preference ---")
    for meal, students in meal_groups.items():
        print(f"{meal}: {', '.join(students)}")

    print("\n--- Weekly Spending per Student ---")
    for name, amount in weekly_spending.items():
        print(f"{name}: {amount:,} UGX")

    print("\n--- High Spenders (> 15,000 UGX/week) ---")
    if high_spenders:
        for name, amount in high_spenders:
            print(f"{name}: {amount:,} UGX")
    else:
        print("None")

    print("\n--- Weekly Revenue per Meal ---")
    for meal, revenue in meal_revenue.items():
        print(f"{meal}: {revenue:,} UGX")

    print(f"\nMost Popular Meal: {popular_meal} ({popular_count} students)")
    print("=" * 50)

    return {
        "meal_groups": meal_groups,
        "weekly_spending": weekly_spending,
        "high_spenders": high_spenders,
        "meal_revenue": meal_revenue,
        "most_popular_meal": popular_meal,
    }


# ---------------- TESTING ----------------
if __name__ == "__main__":
    # 1) Supplied dataset
    meal_data = [
        ("John", "Pizza", 2500),
        ("Sarah", "Burger", 2000),
        ("Mike", "Pasta", 2200),
        ("Grace", "Chicken and Rice", 3500),
        ("Peter", "Pizza", 2500),
    ]
    print("### TEST 1: SUPPLIED DATASET ###")
    generate_report(meal_data)

    # 2) Additional dataset: normal case + edge case
    #    - normal: typical students with varied prices
    #    - edge case: a student spending exactly at the threshold (2900*5=14500, not >15000)
    #                 and one just over it (3100*5=15500 > 15000)
    extra_meal_data = [
        ("Faith", "Rice and Beans", 1800),
        ("Isaac", "Rice and Beans", 1800),
        ("Naomi", "Matooke", 2900),   # edge: weekly = 14,500 (NOT a high spender)
        ("Ben", "Matooke", 3100),     # edge: weekly = 15,500 (IS a high spender)
    ]
    print("\n### TEST 2: ADDITIONAL DATASET (edge cases included) ###")
    generate_report(extra_meal_data)
